### ISSUE TITLE
for loop continue never increase index

### ISSUE THREAD

**Issue by LaysDragon** [mlogjs/mlogjs#107]
for loop continue statement have bug,it will never increase index and turn into infinite loop.
```ts
for(let i=0;i<10;i++){
    continue;
}
print('done');
printFlush();
```
#### compiler output:
```
set i:1:8 0
op lessThan &t0 i:1:8 10
jump 6 equal &t0 0
jump 1 always
op add i:1:8 i:1:8 1
jump 1 always
print "done"
printflush message1
end
```

mlogjs version: 0.4.2

**Comment by JeanJPNM** [comment]
The fix is now available in version 0.4.3

**Comment by LaysDragon** [comment]
nice :)

**Comment by LaysDragon** [comment]
the loop bug still existing in 0.4.3.  
compile output is exactly same.
```
set i:1:8 0
op lessThan &t0 i:1:8 10
jump 6 equal &t0 0
jump 1 always
op add i:1:8 i:1:8 1
jump 1 always
print "done"
printflush message1
end
```

**Comment by JeanJPNM** [comment]
Huh, seems like the version was released with an outdated build. I should deal with this and #73

**Comment by JeanJPNM** [comment]
Ok, now it's actually present in the version 0.4.4
