### ISSUE TITLE
[bug] Using labels in asm breaks jump addresses

### ISSUE THREAD

**Issue by hsaturn** [mlogjs/mlogjs#228]
Hello

  Because MLogJS resolves lines number instead of creating labels, thus, one cannot use any label in asm !
  This leads to wrong jumps.
  In this snippets, the bar function is erroneous.
  Once asm generated code is copied into the game, bar does only flush to message1. The print itself (line 15 in the game) is well generated but the jump to foo (at line 6 in the game) goes to line 16.

``` js
var counter = 0;


while (true)
{
    foo(counter);
    bar(counter + 1);
    counter = counter + 2;
}

function foo(counter) {
    asm`print ${counter}`;
    asm`jump foo always`;
    asm`foo:`;
    asm`printflush message1`;
}

function bar(counter) {
    asm`print ${counter}`;
    asm`jump bar always`;
    asm`bar:`;
    asm`printflush message1`;
}
```

The generated asm
``` js
set counter:1:4 0
set counter:11:13 counter:1:4
set &rfoo:11:0 4
jump 10 always
op add counter:18:13 counter:1:4 1
set &rbar:18:0 7
jump 16 always
op add counter:1:4 counter:1:4 2
jump 1 always
end
print counter:11:13
jump foo always
foo:  ============= <-- line removed by mindustry (causing foo to be altered) ============
printflush message1
set &ffoo:11:0 null
set @counter &rfoo:11:0
print counter:18:13
jump bar always
bar:  <-- line removed by mindustry
printflush message1
set &fbar:18:0 null
set @counter &rbar:18:0
```

The long story is that I made a c++ program that generates a very long optimized asm sequence for drawing on display, with lots of labels. This generated asm code was to be included in a function of my MLogJS code.

MLogJs is great, thanks for this tool !

**Comment by hsaturn** [comment]
Great ! I'm no longer limited in my asm code generated, just copy / paste into a function and all is ok.
Thanks

May I ask why are you keeping unlabeled jumps. All may work fluently if mlogjs was generating labels instead of line jumps.
The only reason I see is that this saves lines in generated code, and maybe the limit of 1000 lines of code for a processor includes labels ?

**Comment by JeanJPNM** [comment]
Well, when mlogjs was originally developed mlog didn't have labels, so the compiler had to resolve the line addresses used by jumps and function calls.

And after they added the main points for not using them were:
- That would be one more naming scheme the compiler had to use and maintain.
- Labels can't be used in places that manipulate the `@counter` variable (function return addresses and the `@counter` arrays)

In the end, even if mlogjs did end up using labels, it would still need to resolve line numbers in the cases above, and the readability of the generated labels would not be as great without some considerable effort put into it.
