### ISSUE TITLE
Strict switch compiler flag

### ISSUE THREAD

**Issue by JeanJPNM** [mlogjs/mlogjs#96]
Let users decide wether they want switch statements to use regular or strict equality.

**Comment by weisrc** [comment]
perhaps it can be done with the use of the JS "use strict";

**Comment by weisrc** [comment]
or even a a function call at the beginning of the scope: `directive({strict: true})`

**Comment by JeanJPNM** [comment]
Implementing this feature would be unidiomatic. The ECMAScript spec says that `switch` `case` statements should only perform strict comparisons.
